// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GoogleMapController from "./google_map_controller"
application.register("google-map", GoogleMapController)

import VoicevoxController from "./voicevox_controller"
application.register("voicevox", VoicevoxController)
